acts_as_archive:
  rake: >=0.8.7
  rspec: ~>1.0
  default:
    active_wrapper-solo: =0.4.4
    also_migrate: =0.3.5
    externals: =1.0.2
    framework_fixture: =0.1.3
    mover: =0.3.6
    rack-test: =0.5.6